# <center> HEART DISEASE PREDICTION </center>

Heart disease prediction using four machine learning models.
1. Logistic Regression
2. Random Forest 
3. K Neareast Neighbor
4. Support Vector Machine

Dataset: Cleveland Heart Disease Dataset

Source:<br> 
1. UCI Machine Learning Repository https://archive.ics.uci.edu/ml/datasets/Heart+Disease <br>
    OR
2. Kaggle, https://www.kaggle.com/ronitf/heart-disease-uci


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Reading the data

dataset = pd.read_csv("heart.csv")

In [3]:
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
#Statistical data insights

dataset.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [5]:
# Checking for any missing values 

dataset.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler(feature_range =(0,100))

In [7]:
# setting scale of max min value for sbp in range of 0-100, normalise

dataset['trestbps'] = scale.fit_transform(dataset['trestbps'].values.reshape(-1,1))
dataset['chol'] = scale.fit_transform(dataset['chol'].values.reshape(-1,1))
dataset['thalach'] = scale.fit_transform(dataset['thalach'].values.reshape(-1,1))

# or 
#dataset['trestbps'] = scale.fit_transform(dataset['trestbps'].values.reshape(-1,1))
#dataset['chol'] = scale.fit_transform(dataset['chol'].values.reshape(-1,1))
#dataset['thalach'] = scale.fit_transform(dataset['thalach'].values.reshape(-1,1))

In [8]:
dataset.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997   35.494115   27.457540    0.148515   
std      9.082101    0.466011    1.032052   16.545418   11.833505    0.356198   
min     29.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%     47.500000    0.000000    0.000000   24.528302   19.406393    0.000000   
50%     55.000000    1.000000    1.000000   33.962264   26.027397    0.000000   
75%     61.000000    1.000000    2.000000   43.396226   33.904110    0.000000   
max     77.000000    1.000000    3.000000  100.000000  100.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053   60.035775    0.326733    1.039604    1.399340    0.729373   
std      0.525860   17.484856    0.469794    1.161075    0.616226    1.022606   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000   47.709924    0.000000    0.000000    1.000000    0.000000   
50%      1.000000   62.595420    0.000000    0.800000    1.000000    0.000000   
75%      1.000000   72.519084    1.000000    1.600000    2.000000    1.000000   
max      2.000000  100.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [9]:
dataset.head(5)

age  sex  cp   trestbps       chol  fbs  restecg    thalach  exang  \
0   63    1   3  48.113208  24.429224    1        0  60.305344      0   
1   37    1   2  33.962264  28.310502    0        1  88.549618      0   
2   41    0   1  33.962264  17.808219    0        0  77.099237      0   
3   56    1   1  24.528302  25.114155    0        1  81.679389      0   
4   57    0   0  24.528302  52.054795    0        1  70.229008      1   

   oldpeak  slope  ca  thal  target  
0      2.3      0   0     1       1  
1      3.5      0   0     2       1  
2      1.4      2   0     2       1  
3      0.8      2   0     2       1  
4      0.6      2   0     2       1

In [10]:
# finding (total number of rows, total number of columns)

dataset.shape

(303, 14)

In [11]:
# indicate x and y using iloc. Syntax is data.iloc[<row selection>, <column selection>] 
# for further understanding of iloc, refer https://www.shanelynn.ie/select-pandas-dataframe-rows-and-columns-using-iloc-loc-and-ix/#iloc-selection 

x = dataset.iloc[:,:13] # first 13 columns of data frame with all rows
y = dataset.iloc[:,13]   # 14th column of data frame (target column)

In [12]:
# splitting the data into test and train  having a test size of 20% and 80% train size
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 1234) 

#or
#from sklearn.model_selection import train_test_split
#x_train, x_test, y_train, y_test = train_test_split(dataset.iloc[:,:13], dataset.iloc[:,13], test_size=0.2, random_state=1234)

# LOGISTIC REGRESSION

In [13]:
from sklearn.linear_model import LogisticRegression
model =LogisticRegression(solver='sag',max_iter=1000)
model.fit(x_train,y_train)


C:\Users\hp\Anaconda3\envs\julios\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='sag', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
res =model.predict(x_test)

In [15]:
res

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,res))
from sklearn.metrics import confusion_matrix
acc =confusion_matrix(y_test,res)
print(acc)

0.7540983606557377
[[19  9]
 [ 6 27]]


In [17]:
recall_lr = acc[0][0]/(acc[0][0] + acc[0][1])
precision_lr = acc[0][0]/(acc[0][0]+acc[1][1])
recall_lr,precision_lr

(0.6785714285714286, 0.41304347826086957)

# RANDOM FOREST

In [38]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=600)


In [39]:
model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [40]:
y_pred = model.predict(x_test)

In [41]:
ran_for = confusion_matrix(y_test,y_pred)
print(ran_for)

[[19  9]
 [ 5 28]]


In [42]:
print(accuracy_score(y_test,y_pred))

0.7704918032786885


In [44]:
recall_rf = ran_for[0][0]/(ran_for[0][0] + ran_for[0][1])
precision_rf = ran_for[0][0]/(ran_for[0][0]+ran_for[1][1])
recall_rf,precision_rf

(0.6785714285714286, 0.40425531914893614)

# KNN

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=14)

In [24]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=14)

In [25]:
model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=14, p=2,
                     weights='uniform')

In [26]:
model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=14, p=2,
                     weights='uniform')

In [27]:
y_pred = model.predict(x_test)

In [45]:
from sklearn.metrics import confusion_matrix
knn = confusion_matrix(y_test,y_pred)

In [46]:
knn

array([[19,  9],
       [ 5, 28]], dtype=int64)

In [28]:
print(accuracy_score(y_test,y_pred))

0.6557377049180327


In [31]:
recall_knn = knn[0][0]/(knn[0][0]+knn[0][1])
precision_knn = knn[0][0]/(knn[0][0]+knn[1][1])
recall_knn,precision_knn

(0.5714285714285714, 0.4)

# SVM

In [32]:
from sklearn import svm
svm_clf = svm.SVC(kernel ='linear')

In [33]:
svm_clf.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [34]:
y_pred_svm =svm_clf.predict(x_test)
y_pred_svm

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0], dtype=int64)

In [35]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_svm = confusion_matrix(y_test, y_pred_svm)
cm_svm

array([[20,  8],
       [ 6, 27]], dtype=int64)

In [36]:
from sklearn.metrics import accuracy_score
svm_result = accuracy_score(y_test,y_pred_svm)
print("Accuracy :",svm_result)

Accuracy : 0.7704918032786885


In [37]:
recall_svm = cm_svm[0][0]/(cm_svm[0][0] + cm_svm[0][1])
precision_svm = cm_svm[0][0]/(cm_svm[0][0]+cm_svm[1][1])
recall_svm,precision_svm

(0.7142857142857143, 0.425531914893617)